### ISSUE TITLE
咨询一下，因为 iptv 会更新，我需要定期更新电视上的 app 吗？

### ISSUE THREAD

**Issue by yoeb** [vbskycn/iptv#11]

**Comment by vbskycn** [comment]
完全不用，用户完全无感，3年前的app都可以正常使用，软件注重本身，不搞一些其他的功能

**Comment by vbskycn** [comment]
完全不用，用户完全无感，3年前的app都可以正常使用，软件注重本身，不搞一些其他的功能

**Comment by vbskycn** [comment]
完全不用，用户完全无感，3年前的app都可以正常使用，软件注重本身，不搞一些其他的功能
