### ISSUE TITLE
跑路了吗？提示网络中断

### ISSUE THREAD

**Issue by JohnSteven2019** [vbskycn/iptv#14]
跑路了吗？提示网络中断

**Comment by vbskycn** [comment]
家里的ip地址有可能因为某些原因被服务器封禁了，所以提示网络中断，你只要重启一下家里的光猫路由器就可以了
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年10月20日 13:15 收件人 ***@***.***> 抄送至 ***@***.***> 主题 [vbskycn/iptv] 跑路了吗？提示网络中断 (Issue #14) 
跑路了吗？提示网络中断

**Comment by JohnSteven2019** [comment]
是吗？怎么我手机开流量了也不能看呢？重启了光猫还是不能看

**Comment by yoeb** [comment]
ipv6 挂掉了

**Comment by JohnSteven2019** [comment]
1.重庆联通手机流量无法访问，家里宽带无法访问（ipv6）
2.重庆电信手机流量正常访问。
请问应该怎么办？？？
