### ISSUE TITLE
重庆联通无法访问

### ISSUE THREAD

**Issue by JohnSteven2019** [vbskycn/iptv#15]
1.重庆联通手机流量无法访问，家里宽带无法访问（ipv6）
2.重庆电信手机流量正常访问。
请问应该怎么办？？？

**Comment by vbskycn** [comment]
近几天确实发现，被重庆联通封了链接域名
后期会换上新域名，如果你看到有新版本发布，那就是重新安装就可以了

**Comment by vbskycn** [comment]
新增特别版，可以试试

https://zbds.lanzoui.com/b0b2kul6b

**Comment by vbskycn** [comment]
https://zbds.lanzoui.com/b0b2kul6b

**Comment by JohnSteven2019** [comment]
特别版可以使用，非常感谢
