### ISSUE TITLE
my-tv-0无法导入live.zbds.top上的在线列表

### ISSUE THREAD

**Issue by Jamwe** [vbskycn/iptv#17]
现象如下：
- 宽带为重庆移动
- 同路由器下，手机和电脑都可以访问和下载[iptv6频道列表](https://live.zbds.top/tv/iptv6.m3u)或[iptv4频道列表](https://live.zbds.top/tv/iptv4.m3u)
- my-tv-0通过上述地址导入在线列表，提示频道请求错误。记得11月之前都可以的。
- 将频道列表下载下来，通过离线文件导入方式就没问题。

**Comment by vbskycn** [comment]
重庆移动把域名给屏蔽了
如果打开失败，请使用加速度地址访问

```
https://ghp.ci/raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv6.txt

https://ghp.ci/raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv6.m3u
```



## 📺 自动扫描直播源 IPTV4：
