### ISSUE TITLE
有些频道在potplayer上可以播放，但放进jellyfin里就不行

### ISSUE THREAD

**Issue by LoSiTeE** [vbskycn/iptv#2]
https://live.fanmingming.com/tv/m3u/ipv6.m3u   中的一些频道，比如海南公共、海南少儿、海南文旅、海南自贸这几个频道。我在家里的PC上用potplayer播放都是正常的，但是放在家里nas的jellyfin里播放就黑屏一直加载，请问这是啥原因？

**Comment by vbskycn** [comment]
jellyfin  emby 不支持
