### ISSUE TITLE
反馈直播源问题

### ISSUE THREAD

**Issue by opeopeopeopeopeopeopeopeopeopeopeopeope** [vbskycn/iptv#22]
1.CCTV直播源很卡
2.一些卫视直播源失效了（不包括大湾区卫视）
3.有频道残余，及时清理

**Comment by opeopeopeopeopeopeopeopeopeopeopeopeope** [comment]
可以参考以下图片
![捕获1](https://github.com/user-attachments/assets/202b6504-58a6-42bb-b11a-e22d3a430289)
![Uploading 捕获2.PNG…]()

**Comment by opeopeopeopeopeopeopeopeopeopeopeopeope** [comment]
谢谢作者！给你五星好评

**Comment by vbskycn** [comment]
目前每6个小时更新一次源
尽量保证可用
