### ISSUE TITLE
添加部分香港电视台

### ISSUE THREAD

**Issue by opeopeopeopeopeopeopeopeopeopeopeopeope** [vbskycn/iptv#23]
m3u参考地址:http://aktv.top/live.m3u

**Comment by opeopeopeopeopeopeopeopeopeopeopeopeope** [comment]
里面的内容如下

**Comment by opeopeopeopeopeopeopeopeopeopeopeopeope** [comment]
#EXTM3U x-tvg-url=""

#EXTINF:1 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/28ai" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 28 AI 智慧賽馬
http://aktv.top/AKTV/live/aktv/28ai/AKTV.m3u8

#EXTINF:2 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/channel5hd" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", Channel 5 HD
http://aktv.top/AKTV/live/aktv/channel5hd/AKTV.m3u8

#EXTINF:3 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/channel8hd" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", Channel 8 HD
http://aktv.top/AKTV/live/aktv/channel8hd/AKTV.m3u8

#EXTINF:4 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/channeluhd" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", Channel U HD
http://aktv.top/AKTV/live/aktv/channeluhd/AKTV.m3u8

#EXTINF:5 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/mytvsuper18" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", myTV SUPER 18台
http://aktv.top/AKTV/live/aktv/mytvsuper18/AKTV.m3u8

#EXTINF:6 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/popc" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", PopC
http://aktv.top/AKTV/live/aktv/popc/AKTV.m3u8

#EXTINF:7 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/rockaction" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", ROCK Action
http://aktv.top/AKTV/live/aktv/rockaction/AKTV.m3u8

#EXTINF:8 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/tvbplus" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", TVB Plus
http://aktv.top/AKTV/live/aktv/tvbplus/AKTV.m3u8

#EXTINF:9 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/tvbs" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", TVBS
http://aktv.top/AKTV/live/aktv/tvbs/AKTV.m3u8

#EXTINF:10 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/tvbs-1" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", TVBS-新聞台
http://aktv.top/AKTV/live/aktv/tvbs-1/AKTV.m3u8

#EXTINF:11 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/tvn" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", tvN
http://aktv.top/AKTV/live/aktv/tvn/AKTV.m3u8

#EXTINF:12 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-12" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 中天亞洲台
http://aktv.top/AKTV/live/aktv/null-12/AKTV.m3u8

#EXTINF:13 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-8" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 中天新聞台
http://aktv.top/AKTV/live/aktv/null-8/AKTV.m3u8

#EXTINF:14 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-10" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 中視
http://aktv.top/AKTV/live/aktv/null-10/AKTV.m3u8

#EXTINF:15 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-15" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 千禧經典台(HK)
http://aktv.top/AKTV/live/aktv/null-15/AKTV.m3u8

#EXTINF:16 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/hk" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 娛樂新聞台(HK)
http://aktv.top/AKTV/live/aktv/hk/AKTV.m3u8

#EXTINF:17 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-9" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 寰宇新聞台
http://aktv.top/AKTV/live/aktv/null-9/AKTV.m3u8

#EXTINF:18 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-13" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 日本全天新聞
http://aktv.top/AKTV/live/aktv/null-13/AKTV.m3u8

#EXTINF:19 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-19" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 明珠剧集台(北美)
http://aktv.top/AKTV/live/aktv/null-19/AKTV.m3u8

#EXTINF:20 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-2" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 明珠台
http://aktv.top/AKTV/live/aktv/null-2/AKTV.m3u8

#EXTINF:21 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-1" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 無線新聞台
http://aktv.top/AKTV/live/aktv/null-1/AKTV.m3u8

#EXTINF:22 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/hk-1" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 美亞電影台(HK)
http://aktv.top/AKTV/live/aktv/hk-1/AKTV.m3u8

#EXTINF:23 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-18" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 翡翠剧集台(北美)
http://aktv.top/AKTV/live/aktv/null-18/AKTV.m3u8

#EXTINF:24 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 翡翠台
http://aktv.top/AKTV/live/aktv/null/AKTV.m3u8

#EXTINF:25 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-17" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 翡翠综合台(北美)
http://aktv.top/AKTV/live/aktv/null-17/AKTV.m3u8

#EXTINF:26 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-11" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 華視
http://aktv.top/AKTV/live/aktv/null-11/AKTV.m3u8

#EXTINF:27 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-6" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 靖天電影台
http://aktv.top/AKTV/live/aktv/null-6/AKTV.m3u8

#EXTINF:28 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-3" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 鳳凰中文
http://aktv.top/AKTV/live/aktv/null-3/AKTV.m3u8

#EXTINF:29 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-4" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 鳳凰資訊
http://aktv.top/AKTV/live/aktv/null-4/AKTV.m3u8

#EXTINF:30 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-5" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 鳳凰香港
http://aktv.top/AKTV/live/aktv/null-5/AKTV.m3u8

#EXTINF:31 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-21" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 黃金翡翠台
http://aktv.top/AKTV/live/aktv/null-21/AKTV.m3u8

#EXTINF:32 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-22" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 龍華日韓台
http://aktv.top/AKTV/live/aktv/null-22/AKTV.m3u8

#EXTINF:33 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-7" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 龍華經典台
http://aktv.top/AKTV/live/aktv/null-7/AKTV.m3u8

#EXTINF:34 group-title="AKTV" aktv-server-group="AKTV" tvg-id="aktv/null-23" tvg-logo="" provider="AKTV" provider-logo="" provider-type="iptv", 龍華電影台
http://aktv.top/AKTV/live/aktv/null-23/AKTV.m3u8

#EXTINF:35 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/axn" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", AXN
http://aktv.top/AKTV/live/aktv2/axn/AKTV.m3u8

#EXTINF:36 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/ifun" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", i-Fun 動漫台
http://aktv.top/AKTV/live/aktv2/ifun/AKTV.m3u8

#EXTINF:37 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/lovenaturehd" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", Love Nature HD
http://aktv.top/AKTV/live/aktv2/lovenaturehd/AKTV.m3u8

#EXTINF:38 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/now" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", Now星影台
http://aktv.top/AKTV/live/aktv2/now/AKTV.m3u8

#EXTINF:39 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/now-1" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", Now爆谷台
http://aktv.top/AKTV/live/aktv2/now-1/AKTV.m3u8

#EXTINF:40 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/viutv99" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", viutv 99
http://aktv.top/AKTV/live/aktv2/viutv99/AKTV.m3u8

#EXTINF:41 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/viutv696" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", viutv6 96
http://aktv.top/AKTV/live/aktv2/viutv696/AKTV.m3u8

#EXTINF:42 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/null-1" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", 无线新闻台(北美)	
http://aktv.top/AKTV/live/aktv2/null-1/AKTV.m3u8

#EXTINF:43 group-title="AKTV" aktv-server-group="AKTV2" tvg-id="aktv2/null" tvg-logo="" provider="AKTV2" provider-logo="" provider-type="iptv", 東森新聞
http://aktv.top/AKTV/live/aktv2/null/AKTV.m3u8

#EXTINF:44 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/animaxhk" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", Animax(HK)
http://aktv.top/AKTV/live/aktv3/animaxhk/AKTV.m3u8

#EXTINF:45 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/astroaec" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", Astro AEC
http://aktv.top/AKTV/live/aktv3/astroaec/AKTV.m3u8

#EXTINF:46 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/astroiqiyi" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", Astro iQIYI
http://aktv.top/AKTV/live/aktv3/astroiqiyi/AKTV.m3u8

#EXTINF:47 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/astroxinghe" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", Astro Xing He 
http://aktv.top/AKTV/live/aktv3/astroxinghe/AKTV.m3u8

#EXTINF:48 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/dw" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", DW
http://aktv.top/AKTV/live/aktv3/dw/AKTV.m3u8

#EXTINF:49 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/france24" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", France 24
http://aktv.top/AKTV/live/aktv3/france24/AKTV.m3u8

#EXTINF:50 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/kix" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", KIX
http://aktv.top/AKTV/live/aktv3/kix/AKTV.m3u8

#EXTINF:51 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/lovenaturehd" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", Love Nature HD
http://aktv.top/AKTV/live/aktv3/lovenaturehd/AKTV.m3u8

#EXTINF:52 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/nhkworldjapan" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", NHK World-Japan
http://aktv.top/AKTV/live/aktv3/nhkworldjapan/AKTV.m3u8

#EXTINF:53 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/nhk" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", NHK東京総合
http://aktv.top/AKTV/live/aktv3/nhk/AKTV.m3u8

#EXTINF:54 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/nickjr" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", Nick Jr
http://aktv.top/AKTV/live/aktv3/nickjr/AKTV.m3u8

#EXTINF:55 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/nickelodeon" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", Nickelodeon
http://aktv.top/AKTV/live/aktv3/nickelodeon/AKTV.m3u8

#EXTINF:56 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/thrill" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", Thrill
http://aktv.top/AKTV/live/aktv3/thrill/AKTV.m3u8

#EXTINF:57 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/zoomoo" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", ZooMoo
http://aktv.top/AKTV/live/aktv3/zoomoo/AKTV.m3u8

#EXTINF:58 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/null-3" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", 亞洲新聞台
http://aktv.top/AKTV/live/aktv3/null-3/AKTV.m3u8

#EXTINF:59 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/null" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", 東方衛視國際頻道
http://aktv.top/AKTV/live/aktv3/null/AKTV.m3u8

#EXTINF:60 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/null-2" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", 無線衛星新聞台
http://aktv.top/AKTV/live/aktv3/null-2/AKTV.m3u8

#EXTINF:61 group-title="AKTV" aktv-server-group="AKTV3" tvg-id="aktv3/4k" tvg-logo="" provider="AKTV3" provider-logo="" provider-type="iptv", 翡翠台4K
http://aktv.top/AKTV/live/aktv3/4k/AKTV.m3u8

**Comment by opeopeopeopeopeopeopeopeopeopeopeopeope** [comment]
#EXTM3U x-tvg-url=""可以省略

**Comment by vbskycn** [comment]
这个加了广告限制，用的是cloudflare分发，速度太慢了
不会加入源
