### ISSUE TITLE
KODI使用IPV6 IPTV源的问题

### ISSUE THREAD

**Issue by coolfist163** [vbskycn/iptv#8]
使用KODI的IPTVsimple插件时，直接使用IPV6.m3u无法播放。查找到原因是：地址后面没有跟”:80"端口。比如：
将
http://[2409:8087:1a01:df::7005]/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3......
更改为
http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3......
即可正常播放。

KODI版本21，IPTVSimple版本为最新

**Comment by vbskycn** [comment]
之前确实没有发现，但这应该是kod的问题，因为http 默认就是80端口，https 默认就是443端口，这99%的软件都是这样认定已设置的
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年09月07日 10:18 收件人 ***@***.***> 抄送至 ***@***.***> 主题 [vbskycn/iptv] KODI使用IPV6 IPTV源的问题 (Issue #8) 
使用KODI的IPTVsimple插件时，直接使用IPV6.m3u无法播放。查找到原因是：地址后面没有跟”:80"端口。比如：
将
http://[2409:8087:1a01:df::7005]/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3......
更改为
http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3......
即可正常播放。
KODI版本21，IPTVSimple版本为最新

**Comment by coolfist163** [comment]
这确实是kodi的问题。电脑上用potplayer是正常的。如果上周及以前的m3u文件都是不带端口号的，那么只能说kodi或者IPTVSimple插件不稳定。因为本周五之前都是没问题的。但我没办法解决这个问题，除非手动更改M3U。发自我的手机-------- 原始邮件 --------发件人： vbskycn ***@***.***>日期： 2024年9月8日周日 08:50收件人： vbskycn/iptv ***@***.***>抄送： coolfist163 ***@***.***>, Author ***@***.***>主    题： Re: [vbskycn/iptv] KODI使用IPV6 IPTV源的问题 (Issue #8)
之前确实没有发现，但这应该是kod的问题，因为http 默认就是80端口，https 默认就是443端口，这99%的软件都是这样认定已设置的
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年09月07日 10:18 收件人 ***@***.***> 抄送至 ***@***.***> 主题 [vbskycn/iptv] KODI使用IPV6 IPTV源的问题 (Issue #8) 
使用KODI的IPTVsimple插件时，直接使用IPV6.m3u无法播放。查找到原因是：地址后面没有跟”:80"端口。比如：
将
http://[2409:8087:1a01:df::7005]/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3......
更改为
http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3......
即可正常播放。
KODI版本21，IPTVSimple版本为最新

**Comment by vbskycn** [comment]
只能是说尽量过滤掉没有80端口的源吧

**Comment by vbskycn** [comment]
已经自动添加所有ipv6地址默认的80端口

**Comment by coolfist163** [comment]
报告两个bug：


1）CCTV1的节目实际为CCTV16，已多次发生。
2）CCTV1~13，特别是CCTV1/2/4经常无台标。下载M3U发现使用“tvg-logo="https://live.fanmingming.com/tv/CCTV2.png" ”，是否换成fanmingming.cn/...会有改善？该站有防机器人机制。


以上问题在KODI，Tivimate均存在。

**Comment by vbskycn** [comment]
好的，会处理好台标的问题
